CREATE TABLE `USER_ORGANIZATION_MAP` (
  `USER_ORG_MAP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `COMPANY_ID` int(11) NOT NULL,
  `INSERT_DT` datetime NOT NULL,
  PRIMARY KEY (`USER_ORG_MAP_ID`),
  KEY `FK_MAP_COMPANY_ID_idx` (`COMPANY_ID`),
  KEY `FK_MAP_USER_ID_idx` (`USER_ID`),
  CONSTRAINT `FK_MAP_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `ORGANIZATION_INFO` (`COMPANY_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_MAP_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `CLIENT_LOGIN_INFO` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)